version: '3'
services:

  node:
    image: aripalo/gatsby-docker
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=8000'
      - 'traefik.frontend.rule=Host:${PROJECT_URL}'
    expose:
      - "8000"
    command: develop

  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
